[workspace]
members = [
    "programs/ziro_delta_amm",
    "programs/ziro_delta_oracle", 
    "programs/ziro_delta_governance",
    "programs/ziro_delta_epoch_manager",
    "programs/ziro_delta_minting",
    "programs/ziro_delta_emergency",
    "programs/mock_oracle"
]

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[programs.localnet]
ziro_delta_amm = "9WzDXwBbmkg8ZTbNMqUxvQRAyrZzDsGYdLVL9zYtAWWM"
ziro_delta_oracle = "8pZdF5QrMk4sGjY6nH7E8P3tA6mD9kR2L1xF5yN7cS4"
ziro_delta_governance = "7nYcM2sB8kF3dP6wE9rT5xL4mH8qR9zA2tK6vJ3eG1N"
ziro_delta_epoch_manager = "6xK8vP3nF7mE2rA5sH9tL4zR6qG8wD3yB5nJ2kC7eM9"
ziro_delta_minting = "5wH9sL3mK8fD2nE6tP4rA7xG5zB8qR9vY2jN6kC3eF8"
ziro_delta_emergency = "4vG8rK2jH6mL9nE3tP7sA5xF4zB9qR8wY6jN3kC2eD7"
mock_oracle = "3uF7qR6jK5mL8nE2tP4sA9xG3zB6qR7wY5jN2kC9eF4"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgradeable = false

[test.validator]
url = "https://api.devnet.solana.com"
commitment = "processed"

[[test.validator.account]]
address = "TokenkegQfeZyiNwAJbNbGKPFXCWuBvf9Ss623VQ5DA"
filename = "tests/fixtures/spl_token-3.5.0.so"

[[test.validator.account]]  
address = "ATokenGPvbdGVxr1b2hvZbsiqW5xWH25efTNsLJA8knL"
filename = "tests/fixtures/spl_associated_token-1.1.2.so" 